---
- name: Install bind
  hosts: dnsaas-bind
  become: true

  vars:

    named_config:
      include: '"/etc/rndc.key"'
      controls:
        - "inet {{ container_address }} port {{ dnsaas_bind_rndc_default_port }} allow { 127.0.0.1; {{ dnsaas_bind_rndc_listen_cidr  }}; } keys {\"rndc-key\"; }"
 
    named_options:
      allow-new-zones: 'yes'
      minimal-responses: 'yes'
      masterfile-format: 'text'

  tasks:
    - name: Copy rndc key
      template:
        src: rndc.key.j2
        dest: /etc/rndc.key
        owner: bind
        group: bind
        mode: '0600'

  roles:
    - rd-ansible-dns-install



- name: Fix up designate configuration
  hosts: designate_all
  become: true

  tasks:
    - name: Ensure rndc tool is present
      package:
        name: bind9utils
        state: present

    - name: Create rndc key
      template:
        src: rndc.key.j2
        dest: /etc/designate/rndc.key
